import os
import re
import sqlite3
from dotenv import load_dotenv

load_dotenv()


AUTO_ID_COLUMNS = {
    "admin_audit_logs": "id",
    "auth_otps": "id",
    "clinical_letters": "id",
    "consultation_messages": "id",
    "consultation_timeline": "id",
    "consultations": "id",
    "customer_care_accounts": "account_id",
    "doctor_ratings": "id",
    "doctor_reviews": "id",
    "doctors": "id",
    "follow_up_appointments": "id",
    "health_tips": "id",
    "internal_messages": "id",
    "investigation_requests": "id",
    "medical_report_requests": "id",
    "operational_error_logs": "id",
    "patient_consents": "id",
    "patients": "id",
    "payments": "id",
    "prescriptions": "id",
    "support_ticket_feedback": "id",
    "support_ticket_logs": "id",
    "support_ticket_messages": "id",
}

BIGINT_COLUMNS = {
    "admin_id",
    "agent_id",
    "created_by_admin_id",
    "doctor_id",
    "doctor_telegram_id",
    "granted_by_admin_id",
    "patient_id",
    "patient_telegram_id",
    "recipient_doctor_id",
    "sender_id",
    "telegram_id",
    "user_id",
}


def get_database_url():
    return os.getenv("DATABASE_URL", "").strip()


def is_postgres_enabled():
    return bool(get_database_url())


def get_database_path():
    return os.getenv("DATABASE_PATH", "synmed.db")


class PostgresCursor:
    def __init__(self, cursor, connection):
        self._cursor = cursor
        self._connection = connection
        self.lastrowid = None

    def __iter__(self):
        return iter(self._cursor)

    def _convert_sql(self, sql: str) -> str:
        converted = sql.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        converted = converted.replace("AUTOINCREMENT", "")
        converted = converted.replace("TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP", "TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)")
        converted = converted.replace("TEXT DEFAULT CURRENT_TIMESTAMP", "TEXT DEFAULT (CURRENT_TIMESTAMP::TEXT)")
        converted = re.sub(r"\s+COLLATE\s+NOCASE\b", "", converted, flags=re.IGNORECASE)
        converted = converted.replace("datetime('now', '-24 hours')", "(NOW() - INTERVAL '24 hours')::TEXT")
        converted = converted.replace('datetime("now", "-24 hours")', "(NOW() - INTERVAL '24 hours')::TEXT")
        converted = re.sub(r"datetime\((COALESCE\([^)]+\))\)", r"\1", converted, flags=re.IGNORECASE)
        converted = re.sub(r"datetime\(([a-zA-Z_][a-zA-Z0-9_\.]*)\)", r"\1", converted, flags=re.IGNORECASE)
        for column in BIGINT_COLUMNS:
            converted = re.sub(
                rf"\b{column}\s+INTEGER\b",
                f"{column} BIGINT",
                converted,
                flags=re.IGNORECASE,
            )
        converted = converted.replace("%", "%%")
        converted = converted.replace("?", "%s")
        return converted

    def _insert_returning_column(self, sql: str) -> str | None:
        if not sql.lstrip().upper().startswith("INSERT "):
            return None
        if re.search(r"\bRETURNING\b", sql, flags=re.IGNORECASE):
            return None
        match = re.search(r"INSERT\s+INTO\s+([a-zA-Z_][a-zA-Z0-9_]*)", sql, flags=re.IGNORECASE)
        if not match:
            return None
        return AUTO_ID_COLUMNS.get(match.group(1).lower())

    def execute(self, sql: str, params=None):
        converted = self._convert_sql(sql)
        returning_column = self._insert_returning_column(converted)
        if returning_column:
            converted = f"{converted.rstrip().rstrip(';')} RETURNING {returning_column}"
        self._cursor.execute(converted, params or ())
        self.lastrowid = None
        if returning_column:
            row = self._cursor.fetchone()
            self.lastrowid = row[returning_column] if row else None
        return self

    def executemany(self, sql: str, seq_of_params):
        self._cursor.executemany(self._convert_sql(sql), seq_of_params)
        self.lastrowid = None
        return self

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def close(self):
        self._cursor.close()


class PostgresConnection:
    def __init__(self, raw_connection):
        self._raw = raw_connection

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        if exc_type:
            self.rollback()
        else:
            self.commit()
        self.close()

    def cursor(self):
        return PostgresCursor(self._raw.cursor(), self)

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    def close(self):
        self._raw.close()


def get_connection():
    database_url = get_database_url()
    if database_url:
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as exc:
            raise RuntimeError("DATABASE_URL is set but psycopg is not installed.") from exc

        return PostgresConnection(psycopg.connect(database_url, row_factory=dict_row))

    conn = sqlite3.connect(get_database_path())
    conn.row_factory = sqlite3.Row
    return conn


def get_table_columns(cursor, table_name: str) -> set[str]:
    if is_postgres_enabled():
        cursor.execute(
            """
            SELECT column_name AS name
            FROM information_schema.columns
            WHERE table_schema = current_schema() AND table_name = ?
            """,
            (table_name,),
        )
    else:
        cursor.execute(f"PRAGMA table_info({table_name})")
    return {row["name"] for row in cursor.fetchall()}


def _column_definition_for_database(column_name: str, definition: str) -> str:
    if not is_postgres_enabled():
        return definition
    converted = definition.replace("AUTOINCREMENT", "")
    if column_name.lower() in BIGINT_COLUMNS:
        converted = re.sub(r"\bINTEGER\b", "BIGINT", converted, count=1, flags=re.IGNORECASE)
    return converted


def rebuild_feedback_table(cursor, table_name: str, value_column: str):
    legacy_name = f"{table_name}_legacy"
    cursor.execute(f"DROP TABLE IF EXISTS {legacy_name}")
    cursor.execute(f"ALTER TABLE {table_name} RENAME TO {legacy_name}")

    value_definition = (
        "INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5)"
        if value_column == "rating"
        else "TEXT NOT NULL"
    )

    cursor.execute(f"""
    CREATE TABLE {table_name} (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        consultation_id TEXT NOT NULL UNIQUE,
        doctor_id INTEGER NOT NULL,
        patient_id INTEGER NOT NULL,
        {value_column} {value_definition},
        created_at TEXT NOT NULL
    )
    """)

    cursor.execute(f"""
    INSERT INTO {table_name} (consultation_id, doctor_id, patient_id, {value_column}, created_at)
    SELECT
        '{table_name}-legacy-' || id,
        COALESCE(CAST(doctor_id AS INTEGER), 0),
        COALESCE(CAST(patient_id AS INTEGER), 0),
        {value_column},
        COALESCE(created_at, CURRENT_TIMESTAMP)
    FROM {legacy_name}
    """)

    cursor.execute(f"DROP TABLE {legacy_name}")


def ensure_feedback_schema(cursor, table_name: str, value_column: str):
    columns = get_table_columns(cursor, table_name)
    expected = {"id", "consultation_id", "doctor_id", "patient_id", value_column, "created_at"}
    if columns and columns != expected and not is_postgres_enabled():
        rebuild_feedback_table(cursor, table_name, value_column)


def ensure_columns(cursor, table_name: str, column_definitions: dict[str, str]):
    existing = get_table_columns(cursor, table_name)
    for column_name, definition in column_definitions.items():
        if column_name not in existing:
            cursor.execute(
                f"ALTER TABLE {table_name} ADD COLUMN {column_name} {_column_definition_for_database(column_name, definition)}"
            )


def init_db():
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS doctors (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        doctor_id TEXT UNIQUE,
        telegram_id INTEGER UNIQUE,
        name TEXT,
        qualification TEXT,
        license_no TEXT,
        signature_path TEXT,
        status TEXT,
        created_at TEXT
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS patients (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        patient_id TEXT UNIQUE,
        telegram_id INTEGER UNIQUE,
        name TEXT,
        age INTEGER,
        gender TEXT,
        phone TEXT,
        created_at TEXT
    )
    """)
    ensure_columns(
        cursor,
        "patients",
        {
            "email": "TEXT",
            "email_verified_at": "TEXT",
            "address": "TEXT",
            "allergy": "TEXT",
            "medical_conditions": "TEXT",
            "password_hash": "TEXT",
            "updated_at": "TEXT",
        },
    )

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS payments (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        reference TEXT NOT NULL UNIQUE,
        telegram_id INTEGER NOT NULL,
        patient_id TEXT,
        email TEXT NOT NULL,
        amount INTEGER NOT NULL,
        currency TEXT NOT NULL,
        patient_type TEXT NOT NULL,
        label TEXT NOT NULL,
        authorization_url TEXT,
        access_code TEXT,
        status TEXT NOT NULL,
        paystack_status TEXT,
        created_at TEXT NOT NULL,
        verified_at TEXT
    )
    """)
    ensure_columns(
        cursor,
        "payments",
        {
            "payment_token": "TEXT",
            "payment_token_used_at": "TEXT",
            "registration_payload_json": "TEXT",
            "access_expires_at": "TEXT",
            "grant_reason": "TEXT",
            "granted_by_admin_id": "INTEGER",
        },
    )

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS dismissed_payment_attention (
        patient_id TEXT PRIMARY KEY,
        dismissed_by_role TEXT,
        dismissed_by_id TEXT,
        dismissed_at TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS consultations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        consultation_id TEXT UNIQUE,
        patient_id TEXT,
        doctor_id TEXT,
        status TEXT,
        notes TEXT,
        created_at TEXT,
        closed_at TEXT
    )
    """)
    ensure_columns(
        cursor,
        "consultations",
        {
            "patient_telegram_id": "INTEGER",
            "doctor_telegram_id": "INTEGER",
            "doctor_private_notes": "TEXT",
            "diagnosis": "TEXT",
            "saved_at": "TEXT",
            "payment_reference": "TEXT",
        },
    )

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS consultation_messages (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        consultation_id TEXT NOT NULL,
        sender_id INTEGER NOT NULL,
        sender_role TEXT NOT NULL,
        message_text TEXT NOT NULL,
        created_at TEXT NOT NULL
    )
    """)
    ensure_columns(
        cursor,
        "consultation_messages",
        {
            "asset_path": "TEXT",
            "asset_type": "TEXT",
        },
    )

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS consultation_timeline (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        consultation_id TEXT NOT NULL,
        event_type TEXT NOT NULL,
        actor_id TEXT,
        details TEXT,
        created_at TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS admin_audit_logs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        admin_id INTEGER NOT NULL,
        action TEXT NOT NULL,
        target_type TEXT NOT NULL,
        target_id TEXT NOT NULL,
        details TEXT,
        created_at TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS follow_up_appointments (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        appointment_id TEXT NOT NULL UNIQUE,
        consultation_id TEXT NOT NULL,
        patient_id TEXT NOT NULL,
        doctor_id TEXT NOT NULL,
        scheduled_for TEXT NOT NULL,
        notes TEXT,
        status TEXT NOT NULL,
        created_at TEXT NOT NULL
    )
    """)
    ensure_columns(
        cursor,
        "follow_up_appointments",
        {
            "reminder_sent_at": "TEXT",
            "payment_status": "TEXT DEFAULT 'unpaid'",
            "payment_reference": "TEXT",
            "payment_token": "TEXT",
            "confirmed_at": "TEXT",
        },
    )

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS prescriptions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        rx_id TEXT,
        consultation_id TEXT,
        doctor_id TEXT,
        patient_id TEXT,
        version INTEGER,
        medication_json TEXT,
        notes TEXT,
        is_latest INTEGER,
        created_at TEXT
    )
    """)
    ensure_columns(
        cursor,
        "prescriptions",
        {
            "asset_path": "TEXT",
            "asset_type": "TEXT",
        },
    )

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS investigation_requests (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        request_id TEXT,
        consultation_id TEXT,
        doctor_id TEXT,
        patient_id TEXT,
        diagnosis TEXT,
        tests_text TEXT,
        notes TEXT,
        created_at TEXT
    )
    """)
    ensure_columns(
        cursor,
        "investigation_requests",
        {
            "asset_path": "TEXT",
            "asset_type": "TEXT",
        },
    )

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS clinical_letters (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        letter_id TEXT NOT NULL UNIQUE,
        consultation_id TEXT NOT NULL,
        doctor_id TEXT NOT NULL,
        patient_id TEXT NOT NULL,
        letter_type TEXT NOT NULL,
        diagnosis TEXT,
        body_text TEXT NOT NULL,
        target_hospital TEXT,
        notes TEXT,
        created_at TEXT NOT NULL,
        asset_path TEXT,
        asset_type TEXT
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS admin_alert_states (
        admin_id INTEGER NOT NULL,
        alert_id TEXT NOT NULL,
        alert_signature TEXT NOT NULL,
        reviewed_at TEXT,
        dismissed_at TEXT,
        updated_at TEXT NOT NULL,
        PRIMARY KEY (admin_id, alert_id, alert_signature)
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS internal_messages (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        sender_role TEXT NOT NULL,
        sender_id TEXT NOT NULL,
        recipient_role TEXT NOT NULL,
        recipient_id TEXT NOT NULL,
        subject TEXT NOT NULL,
        body TEXT,
        attachment_name TEXT,
        attachment_url TEXT,
        attachment_type TEXT,
        read_at TEXT,
        created_at TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS operational_error_logs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        source TEXT NOT NULL,
        severity TEXT NOT NULL,
        message TEXT NOT NULL,
        path TEXT,
        method TEXT,
        status_code INTEGER,
        user_role TEXT,
        user_id TEXT,
        details TEXT,
        created_at TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS medical_report_requests (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        request_id TEXT NOT NULL UNIQUE,
        patient_id TEXT NOT NULL,
        consultation_id TEXT,
        doctor_id TEXT,
        request_note TEXT,
        status TEXT NOT NULL,
        payment_status TEXT NOT NULL,
        payment_reference TEXT,
        payment_token TEXT,
        fulfilled_letter_id TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """)
    ensure_columns(
        cursor,
        "medical_report_requests",
        {
            "delivery_email": "TEXT",
        },
    )

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS partner_facilities (
        partner_id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        partner_type TEXT NOT NULL,
        email TEXT,
        phone TEXT,
        address TEXT,
        contact_person TEXT,
        status TEXT NOT NULL DEFAULT 'pending',
        notes TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS partner_requests (
        request_id TEXT PRIMARY KEY,
        partner_id TEXT NOT NULL,
        document_kind TEXT NOT NULL,
        document_id TEXT,
        consultation_id TEXT,
        patient_id TEXT,
        doctor_id TEXT,
        status TEXT NOT NULL DEFAULT 'sent',
        request_note TEXT,
        partner_note TEXT,
        result_attachment_name TEXT,
        result_attachment_url TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY(partner_id) REFERENCES partner_facilities(partner_id)
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS admin_accounts (
        admin_id INTEGER PRIMARY KEY,
        email TEXT NOT NULL UNIQUE,
        display_name TEXT,
        password_hash TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS admin_email_reminders (
        reminder_key TEXT PRIMARY KEY,
        sent_at TEXT NOT NULL,
        details TEXT
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS customer_care_accounts (
        account_id INTEGER PRIMARY KEY AUTOINCREMENT,
        email TEXT NOT NULL UNIQUE,
        display_name TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        created_by_admin_id INTEGER,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        last_login_at TEXT
    )
    """)
    ensure_columns(
        cursor,
        "customer_care_accounts",
        {
            "status": "TEXT NOT NULL DEFAULT 'active'",
            "created_by_admin_id": "INTEGER",
            "last_login_at": "TEXT",
        },
    )

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS support_tickets (
        ticket_id TEXT PRIMARY KEY,
        patient_id TEXT,
        patient_name TEXT,
        contact_email TEXT,
        topic TEXT NOT NULL,
        summary TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'open',
        source TEXT NOT NULL DEFAULT 'ai_support',
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        resolved_at TEXT
    )
    """)
    ensure_columns(
        cursor,
        "support_tickets",
        {
            "contact_email": "TEXT",
        },
    )

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS support_ticket_messages (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        ticket_id TEXT NOT NULL,
        sender_role TEXT NOT NULL,
        sender_id TEXT,
        message_text TEXT NOT NULL,
        read_at TEXT,
        created_at TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS support_ticket_logs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        ticket_id TEXT NOT NULL,
        actor_role TEXT NOT NULL,
        actor_id TEXT,
        action TEXT NOT NULL,
        note TEXT,
        created_at TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS support_ticket_feedback (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        ticket_id TEXT NOT NULL UNIQUE,
        patient_id TEXT,
        contact_email TEXT,
        rating INTEGER CHECK(rating BETWEEN 1 AND 5),
        review TEXT,
        skipped INTEGER NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS patient_consents (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        telegram_id INTEGER NOT NULL UNIQUE,
        agreed_at TEXT NOT NULL,
        policy_version TEXT NOT NULL,
        channel TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS doctor_ratings (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        consultation_id TEXT NOT NULL UNIQUE,
        doctor_id INTEGER NOT NULL,
        patient_id INTEGER NOT NULL,
        rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),
        created_at TEXT NOT NULL
    )
    """)
    ensure_feedback_schema(cursor, "doctor_ratings", "rating")

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS doctor_reviews (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        consultation_id TEXT NOT NULL UNIQUE,
        doctor_id INTEGER NOT NULL,
        patient_id INTEGER NOT NULL,
        review TEXT NOT NULL,
        created_at TEXT NOT NULL
    )
    """)
    ensure_feedback_schema(cursor, "doctor_reviews", "review")

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS doctor_profiles (
        telegram_id INTEGER PRIMARY KEY,
        name TEXT,
        specialty TEXT,
        experience TEXT,
        license_id TEXT,
        license_file_id TEXT,
        license_file_type TEXT,
        username TEXT,
        verified INTEGER NOT NULL DEFAULT 0
    )
    """)
    ensure_columns(
        cursor,
        "doctor_profiles",
        {
            "phone": "TEXT",
            "email": "TEXT",
            "password_hash": "TEXT",
            "license_expiry_date": "TEXT",
            "license_file_name": "TEXT",
            "license_file_size": "INTEGER",
            "license_reminder_sent_at": "TEXT",
            "updated_at": "TEXT",
        },
    )

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS pending_doctor_requests (
        telegram_id INTEGER PRIMARY KEY,
        name TEXT,
        specialty TEXT,
        experience TEXT,
        license_id TEXT,
        username TEXT,
        file_id TEXT,
        file_type TEXT,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """)
    ensure_columns(
        cursor,
        "pending_doctor_requests",
        {
            "email": "TEXT",
            "phone": "TEXT",
            "password_hash": "TEXT",
            "license_expiry_date": "TEXT",
            "review_status": "TEXT NOT NULL DEFAULT 'pending_review'",
            "submitted_at": "TEXT",
            "reviewed_at": "TEXT",
            "review_note": "TEXT",
            "license_file_name": "TEXT",
            "license_file_size": "INTEGER",
        },
    )

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS doctor_runtime_presence (
        doctor_id INTEGER PRIMARY KEY,
        status TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS waiting_patients_runtime (
        patient_id INTEGER PRIMARY KEY,
        queue_position INTEGER NOT NULL,
        details_json TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS active_consultations_runtime (
        consultation_id TEXT PRIMARY KEY,
        patient_id INTEGER NOT NULL,
        doctor_id INTEGER NOT NULL,
        patient_details_json TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS consultation_calls_runtime (
        consultation_id TEXT PRIMARY KEY,
        state_json TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS support_runtime_presence (
        agent_id INTEGER PRIMARY KEY,
        status TEXT NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS support_waiting_runtime (
        user_id INTEGER PRIMARY KEY,
        queue_position INTEGER NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS support_active_chats_runtime (
        session_id TEXT NOT NULL UNIQUE,
        user_id INTEGER PRIMARY KEY,
        agent_id INTEGER NOT NULL
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS auth_otps (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        role TEXT NOT NULL,
        identifier TEXT NOT NULL,
        delivery_target TEXT NOT NULL,
        code_hash TEXT NOT NULL,
        expires_at TEXT NOT NULL,
        consumed_at TEXT,
        context_json TEXT,
        created_at TEXT NOT NULL
    )
    """)
    ensure_columns(
        cursor,
        "auth_otps",
        {
            "context_json": "TEXT",
        },
    )

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS health_tips (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        eyebrow TEXT NOT NULL,
        title TEXT NOT NULL,
        body TEXT NOT NULL,
        sort_order INTEGER NOT NULL DEFAULT 0,
        is_active INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT
    )
    """)
    ensure_columns(
        cursor,
        "health_tips",
        {
            "audience": "TEXT NOT NULL DEFAULT 'landing'",
        },
    )

    conn.commit()

    cursor.execute("SELECT COUNT(*) AS total FROM health_tips")
    row = cursor.fetchone()
    if not row or row["total"] == 0:
        cursor.executemany(
            """
            INSERT INTO health_tips (eyebrow, title, body, sort_order, is_active, created_at)
            VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
            """,
            [
                (
                    "Health Tip",
                    "Drink water regularly, not only when you feel thirsty.",
                    "Mild dehydration can worsen headaches, tiredness, and poor concentration, especially during hot days.",
                    1,
                    1,
                ),
                (
                    "Health Tip",
                    "Check blood pressure early if headaches keep returning.",
                    "Routine checks help catch silent problems like hypertension before they become emergencies.",
                    2,
                    1,
                ),
                (
                    "Health Tip",
                    "Do not self-medicate repeatedly for the same symptoms.",
                    "When symptoms keep coming back, a proper consultation is usually safer than trying another drug on your own.",
                    3,
                    1,
                ),
                (
                    "SynMed Update",
                    "Keep your medical profile updated for faster care.",
                    "Accurate allergies, phone number, and previous diagnoses help doctors make quicker and safer decisions.",
                    4,
                    1,
                ),
            ],
        )
        conn.commit()

    conn.close()
