NAME, AGE, GENDER, HISTORY = range(4)
REVIEW = 5
DOC_DIAGNOSIS, DOC_ITEMS, DOC_NOTES, DOC_MED_ROUTE, DOC_MED_NAME, DOC_MED_DOSE, DOC_MED_DURATION, DOC_MED_NEXT, DOC_REVIEW, DOC_INVESTIGATION_ITEM, DOC_INVESTIGATION_NEXT = range(6, 17)
